# Generated by Django 2.2.4 on 2022-09-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valid', '0002_auto_20220927_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(),
        ),
    ]
