# Generated by Django 2.2.4 on 2022-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valid', '0003_auto_20220928_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
