# Generated by Django 2.2.4 on 2022-09-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_aouthers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aouther',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
