# Generated by Django 2.2.4 on 2022-09-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_aouthers', '0002_auto_20220926_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='aouther',
            name='note',
            field=models.TextField(default='programeer', max_length=255),
            preserve_default=False,
        ),
    ]
