# Generated by Django 2.2.4 on 2022-09-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_aouthers', '0004_auto_20220926_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aouther',
            name='note',
            field=models.TextField(default='no note for this Auther', max_length=255),
        ),
    ]
