# Generated by Django 2.2.4 on 2022-10-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='Message',
            new_name='Messagee',
        ),
    ]
